sudo: required

services:
 - docker

before_install:
  - docker build -t savioabuga/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true savioabuga/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-707518420290"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"