sudo: required

services:
 - docker

before_install:
  - docker build -t savioabuga/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true savioabuga/docker-react npm run test -- --coverage
